spring:
  application:
    name: Free-Polling-Application
  config:
    import: classpath:private/application-test.yaml, classpath:private/application-dev.yaml, classpath:private/application-prod.yaml