spring:
  application:
    name: Gollaba-Application
  config:
    import:
      - classpath:private/application-test.yaml
      - classpath:private/application-dev.yaml
      - classpath:private/application-prod.yaml
      - classpath:private/application-https.yaml