# This is a basic workflow to help you get started with Actionshttps://github.com/Moon-Jang/Gollaba-Application/settings
name: backend-build-prod
on:
  push:
    branches: [ "master-back" ]

jobs:
  back-end-build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          timeout: 40s
          script: |
            cd Gollaba-Application/backend
            git checkout master-back
            git pull
            git submodule update --remote --merge
            ./gradlew clean build || exit
            sudo docker rm -f gollaba-springboot-prod
            sudo docker rmi -f gollaba-application/springboot-prod
            sudo docker build -t gollaba-application/springboot-prod .
            sudo docker run -d --name gollaba-springboot-prod -p 8081:8080 -e PROFILES=prod gollaba-application/springboot-prod
      - name: SSH
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DEPLOY_WEBHOOK_PROD }}
